version: '3.3'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - .env 
    restart: always

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
